[build]
command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build"
publish = "build"

[build.environment]
NPM_FLAGS = "--version"

[functions]
node_bundler = "esbuild"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "image/png"
